### PR TITLE
Custom address & initialisation check

### PR DESCRIPTION
**Pull request by Gilbocc**
Hi, first of all thanks for your great work. In one of my projects I recently had the need to use a custom address for the hih sensor so I though that would have been cool to add this feature to the library. It only needed a new constructor. Moreover, in order to check te presence of the sensor at initialisation time, I added a single read in the initialise method and returned the resulting value as output of this phase. I hope this suggestions could be useful to improve this great library :)

### CODE REVIEW

**Comment by stevemarple** [comment]
That looks good. I think I had probably intended to allow what you have done but just never added it. Is there a specific reason you added a new constructor rather than adding a parameter with a default value to the existing constructor? I'm just thinking about keeping the code small for memory footprint and maintainability.

**Comment by Gilbocc** [comment]
I'm afraid this is only a symptom of too much Java use. The default parameter is perfect.

**Comment by stevemarple** [comment]
Looking over this more closely I see you have changed 
`template <class T> HIH61xx<T>::HIH61xx(T &i2c) : _address(defaultAddress)`
to
`template <class T> HIH61xx<T>::HIH61xx(T &i2c) : HIH61xx(i2c, defaultAddress)`
which looks like you are trying to have the constructor call itself. 

I think it is better to change (my) line 26 from
`HIH61xx(T &i2c);`
to
`HIH61xx(T &i2c, uint8_t address=defaultAddress);`
to make it take an extra parameter, with a default value, and then (my) line 84 becomes
`template <class T> HIH61xx<T>::HIH61xx(T &i2c, uint8_t address) : _address(address),`

I think that is clearer to read and a smaller change. (I've not actually made the changes to check it compiles.)

The correction to my line 132 (`_i2c.beginTransmission(defaultAddress);` => `_i2c.beginTransmission(_address);`) is a good spot.

Do you want to modify the pull request to do this or should I make those changes?

I see you have removed the printing that notified of error conditions. I don't object greatly but worry that important information is lost. I think the best action would be for me to allow the user to register a callback that is run when an error condition is detected. The examples can be then be modified to put back the printing by using the callback. That should be done after we have merged these changes.

**Comment by Gilbocc** [comment]
As for this sintax

` template <class T> HIH61xx<T>::HIH61xx(T &i2c) : HIH61xx(i2c, defaultAddress)`

it should be legal in the grammar. I think constructor delegation has been introduced pretty recently ([microsoft resource](https://docs.microsoft.com/it-it/cpp/cpp/delegating-constructors?view=msvc-160)). Anyway I completely agree with you that the default parameter version is cleaner.

Regarding your second point, my only concerne was to avoid uncontrolled prints coming from the library. I have been probably too radical to cut them off. Maybe a simpler solution would be to sorround those lines with an `#ifdef SOMETHING` and let the user define that `SOMETHING` outside the library in case of need.

Anyway I'll modify my commit with the constructor fix and the reintroduction of the prints.

**Comment by stevemarple** [comment]
Thanks for making those changes. I squashed them all into one commit and rebased onto the master branch. I noticed a problem in `initialise()`, the `read()` command would be issued before the power-up sequence had finished. I didn't add a delay since the state machine is supposed to be responsible for that timing and 75ms seems a long time to be blocking.

As discussed earlier I removed the print commands and added some callback functions. The examples have been updated to demonstrate this behaviour.

I don't have a HIH61xx device available for testing so unfortunately I cannot check everything works, although all the examples do compile. The power-up error handler does run as expected. If you do find this all works correctly please let me know and I'll bump the version number so that the new code is available through the Arduino library manager.

Thank you for your contribution, I have created a list of contributors and included you on that.

**Comment by Gilbocc** [comment]
I have tested this version with multiple sensors running simultaneously and it works like a charm. 

The only note is on the signature: `template <class T> bool HIH61xx<T>::initialise(uint8_t powerPin)`  changed to  `template <class T> void HIH61xx<T>::initialise(uint8_t powerPin)`. This breaks backward compatibility and shold be well signalled.

I want to thank you for your time and for all the works you do for the community. Keep up the good work :)

**Comment by stevemarple** [comment]
I've bumped the version to 3.0.0 since I think an increase in major version is the clearest way I can signal that breaking change and the new callback handlers. I should add a changelog to the repository but I see creating some good documentation as a higher priority. I've like to do this using the [ArduinoDocs](https://github.com/circuitar/ArduinoDocs) tools to publish to [Read the Docs](https://readthedocs.org/) as I have done with the [AsyncDelay](https://github.com/stevemarple/AsyncDelay) and [MicroNMEA](https://github.com/stevemarple/MicroNMEA) repositories.

Thanks for testing and contributing.

**Pull request closed without merging**
